### ISSUE TITLE
Problem Adding Multiple Controls

### ISSUE THREAD

**Issue by larrytodd** [zumero/DataGrid#3]
The DataGrid does not work when there are multiple controls on a ContentPage.

The headers show, but the bound data does not. The data shows when the DataGrid is the only control on the page

I am using Xamarin Studio on a Mac and am running the App on a simulator.
Xamairn.Forms version 1.5.0.6447

The page is set up like this:
A StackLayout with two StackLayouts inside it. Inside the first StackLayout is a label with some text. Inside the second StackLayout is the DataGrid.

**Comment by jeremysheeley** [comment]
I'm unable to reproduce the reported problem. Are you sure that the data grid and all of the controls that host it have their VerticalOptions set to FillAndExpand?

**Comment by larrytodd** [comment]
No. I did not. I had the property set in all the StackLayout controls, but not the DataGrid. That fixed it. Thanks
